export const words = [
  { lv: "suns", en: "dog" },
  { lv: "kaķis", en: "cat" },
  { lv: "maize", en: "bread" },
  { lv: "ūdens", en: "water" },
  { lv: "piens", en: "milk" },
  { lv: "zivs", en: "fish" },
  { lv: "putns", en: "bird" },
  { lv: "koks", en: "tree" },
  { lv: "māja", en: "house" },
  { lv: "skola", en: "school" },
  { lv: "draugs", en: "friend" },
  { lv: "grāmata", en: "book" },
  { lv: "pilsēta", en: "city" },
  { lv: "valsts", en: "country" },
  { lv: "cilvēks", en: "person" },
  { lv: "bērns", en: "child" },
  { lv: "vecāki", en: "parents" },
  { lv: "mamma", en: "mother" },
  { lv: "tēvs", en: "father" },
  { lv: "brālis", en: "brother" },
  { lv: "māsa", en: "sister" },
  { lv: "zēns", en: "boy" },
  { lv: "meitene", en: "girl" },
  { lv: "skolotājs", en: "teacher" },
  { lv: "students", en: "student" },
  { lv: "mašīna", en: "car" },
  { lv: "velosipēds", en: "bicycle" },
  { lv: "autobuss", en: "bus" },
  { lv: "vilciens", en: "train" },
  { lv: "lidojums", en: "flight" },
  { lv: "ceļš", en: "road" },
  { lv: "iela", en: "street" },
  { lv: "tilts", en: "bridge" },
  { lv: "upe", en: "river" },
  { lv: "ezers", en: "lake" },
  { lv: "jūra", en: "sea" },
  { lv: "mežs", en: "forest" },
  { lv: "kalns", en: "mountain" },
  { lv: "zāle", en: "grass" },
  { lv: "zieds", en: "flower" },
  { lv: "auglis", en: "fruit" },
  { lv: "dārzs", en: "garden" },
  { lv: "ābols", en: "apple" },
  { lv: "banāns", en: "banana" },
  { lv: "apelsīns", en: "orange" },
  { lv: "vīnogas", en: "grapes" },
  { lv: "zeme", en: "earth" },
  { lv: "saule", en: "sun" },
  { lv: "mēness", en: "moon" },
  { lv: "zvaigzne", en: "star" },
  { lv: "debesis", en: "sky" },
  { lv: "lietus", en: "rain" },
  { lv: "sniegs", en: "snow" },
  { lv: "vējš", en: "wind" },
  { lv: "auksts", en: "cold" },
  { lv: "karsts", en: "hot" },
  { lv: "silts", en: "warm" },
  { lv: "foršs", en: "cool" },
  { lv: "liels", en: "big" },
  { lv: "mazs", en: "small" },
  { lv: "jauns", en: "young" },
  { lv: "vecs", en: "old" },
  { lv: "jauns", en: "new" },
  { lv: "vecs", en: "old" },
  { lv: "labs", en: "good" },
  { lv: "slikts", en: "bad" },
  { lv: "skaists", en: "beautiful" },
  { lv: "neglīts", en: "ugly" },
  { lv: "garš", en: "long" },
  { lv: "īs", en: "short" },
  { lv: "augsts", en: "tall" },
  { lv: "zems", en: "low" },
  { lv: "biezs", en: "thick" },
  { lv: "plāns", en: "thin" },
  { lv: "smags", en: "heavy" },
  { lv: "viegls", en: "light (weight)" },
  { lv: "tumšs", en: "dark" },
  { lv: "gaišs", en: "light (bright)" },
  { lv: "ātrs", en: "fast" },
  { lv: "lēns", en: "slow" },
  { lv: "tīrs", en: "clean" },
  { lv: "netīrs", en: "dirty" },
  { lv: "stiprs", en: "strong" },
  { lv: "vājš", en: "weak" },
  { lv: "draudzīgs", en: "friendly" },
  { lv: "laimīgs", en: "happy" },
  { lv: "skumjš", en: "sad" },
  { lv: "dusmīgs", en: "angry" },
  { lv: "mierīgs", en: "calm" },
  { lv: "bailīgs", en: "afraid" },
  { lv: "izsalcis", en: "hungry" },
  { lv: "izslāpis", en: "thirsty" },
  { lv: "noguris", en: "tired" },
  { lv: "slims", en: "sick" },
  { lv: "vesels", en: "healthy" },
  { lv: "bagāts", en: "rich" },
  { lv: "nabadzīgs", en: "poor" },
  { lv: "gudrs", en: "smart" },
  { lv: "muļķīgs", en: "silly" },
  { lv: "spēcīgs", en: "powerful" },
  { lv: "vājš", en: "weak" },
  { lv: "balts", en: "white" },
  { lv: "melns", en: "black" },
  { lv: "sarkans", en: "red" },
  { lv: "zils", en: "blue" },
  { lv: "zaļš", en: "green" },
  { lv: "dzeltens", en: "yellow" },
  { lv: "brūns", en: "brown" },
  { lv: "pelēks", en: "gray" },
  { lv: "rozā", en: "pink" },
  { lv: "oranžs", en: "orange (color)" },
  { lv: "violets", en: "purple" },
  { lv: "zelts", en: "gold" },
  { lv: "sudrabs", en: "silver" },
  { lv: "viens", en: "one" },
  { lv: "divi", en: "two" },
  { lv: "trīs", en: "three" },
  { lv: "četri", en: "four" },
  { lv: "pieci", en: "five" },
  { lv: "seši", en: "six" },
  { lv: "septiņi", en: "seven" },
  { lv: "astoņi", en: "eight" },
  { lv: "deviņi", en: "nine" },
  { lv: "desmit", en: "ten" },
  { lv: "jā", en: "yes" },
  { lv: "nē", en: "no" },
  { lv: "lūdzu", en: "please" },
  { lv: "paldies", en: "thank you" },
  { lv: "atvainojiet", en: "sorry" },
  { lv: "sveiki", en: "hello" },
  { lv: "uz redzēšanos", en: "goodbye" },
  { lv: "labrīt", en: "good morning" },
  { lv: "labdien", en: "good afternoon" },
  { lv: "labvakar", en: "good evening" },
  { lv: "ar labu nakti", en: "good night" },
  { lv: "kā jums klājas?", en: "how are you?" },
  { lv: "labi", en: "fine" },
  { lv: "slikti", en: "badly" },
  { lv: "kur?", en: "where?" },
  { lv: "kad?", en: "when?" },
  { lv: "kāpēc?", en: "why?" },
  { lv: "kas?", en: "what?" },
  { lv: "kā?", en: "how?" },
  { lv: "kurš?", en: "which?" },
  { lv: "cik?", en: "how much?" },
  { lv: "es", en: "I" },
  { lv: "tu", en: "you (singular)" },
  { lv: "viņš", en: "he" },
  { lv: "viņa", en: "she" },
  { lv: "mēs", en: "we" },
  { lv: "jūs", en: "you (plural)" },
  { lv: "viņi", en: "they (masc.)" },
  { lv: "viņas", en: "they (fem.)" },
  { lv: "būt", en: "to be" },
  { lv: "iet", en: "to go" },
  { lv: "nākt", en: "to come" },
  { lv: "redzēt", en: "to see" },
  { lv: "dzirdēt", en: "to hear" },
  { lv: "ēst", en: "to eat" },
  { lv: "dzert", en: "to drink" },
  { lv: "gulēt", en: "to sleep" },
  { lv: "strādāt", en: "to work" },
  { lv: "spēlēt", en: "to play" },
  { lv: "lasīt", en: "to read" },
  { lv: "rakstīt", en: "to write" },
  { lv: "domāt", en: "to think" },
  { lv: "zināt", en: "to know" },
  { lv: "mācīties", en: "to learn" },
  { lv: "mācīt", en: "to teach" },
  { lv: "pirkt", en: "to buy" },
  { lv: "pārdot", en: "to sell" },
  { lv: "atvērt", en: "to open" },
  { lv: "aizvērt", en: "to close" },
  { lv: "sākt", en: "to start" },
  { lv: "beigt", en: "to finish" },
  { lv: "palīdzēt", en: "to help" },
  { lv: "spēt", en: "to be able" },
  { lv: "gribēt", en: "to want" },
  { lv: "patikt", en: "to like" },
  { lv: "mīlēt", en: "to love" },
  { lv: "baidīties", en: "to fear" },
  { lv: "cerēt", en: "to hope" },
  { lv: "smaidīt", en: "to smile" },
  { lv: "smieties", en: "to laugh" },
  { lv: "raudāt", en: "to cry" },
  { lv: "sēdēt", en: "to sit" },
  { lv: "stāvēt", en: "to stand" },
  { lv: "skriet", en: "to run" },
  { lv: "peldēt", en: "to swim" },
  { lv: "lidot", en: "to fly" },
  { lv: "braukt", en: "to drive" },
  { lv: "zvanīt", en: "to call" },
  { lv: "runāt", en: "to speak" },
  { lv: "klausīties", en: "to listen" },
  { lv: "skatīties", en: "to watch" },
  { lv: "meklēt", en: "to search" },
  { lv: "atrast", en: "to find" },
  { lv: "zaudēt", en: "to lose" },
  { lv: "uzvarēt", en: "to win" },
  { lv: "sāpes", en: "pain" },
  { lv: "prieks", en: "joy" },
  { lv: "mīlestība", en: "love (noun)" },
  { lv: "naids", en: "hate" },
  { lv: "bailes", en: "fear" },
  { lv: "cerība", en: "hope" },
  { lv: "sapnis", en: "dream" },
  { lv: "dzīve", en: "life" },
  { lv: "nāve", en: "death" },
  { lv: "laiks", en: "time" },
  { lv: "diena", en: "day" },
  { lv: "nakts", en: "night" },
  { lv: "rīts", en: "morning" },
  { lv: "vakars", en: "evening" },
  { lv: "nedēļa", en: "week" },
  { lv: "mēnesis", en: "month" },
  { lv: "gads", en: "year" },
  { lv: "stunda", en: "hour" },
  { lv: "minūte", en: "minute" },
  { lv: "sekunde", en: "second" },
  { lv: "tagad", en: "now" },
  { lv: "vakar", en: "yesterday" },
  { lv: "šodien", en: "today" },
  { lv: "rīt", en: "tomorrow" },
  { lv: "vienmēr", en: "always" },
  { lv: "nekad", en: "never" },
  { lv: "bieži", en: "often" },
  { lv: "reti", en: "rarely" },
  { lv: "reizēm", en: "sometimes" },
  { lv: "drīz", en: "soon" },
  { lv: "vēlāk", en: "later" },
  { lv: "agrāk", en: "earlier" },
  { lv: "pirms", en: "before" },
  { lv: "pēc", en: "after" },
  { lv: "iekšā", en: "inside" },
  { lv: "ārā", en: "outside" },
  { lv: "augšā", en: "up" },
  { lv: "lejā", en: "down" },
  { lv: "pa kreisi", en: "left" },
  { lv: "pa labi", en: "right" },
  { lv: "priekšā", en: "in front" },
  { lv: "aizmugurē", en: "behind" },
  { lv: "tuvumā", en: "near" },
  { lv: "tālu", en: "far" },
  { lv: "blakus", en: "next to" },
  { lv: "starp", en: "between" },
  { lv: "virs", en: "above" },
  { lv: "zem", en: "below" },
  { lv: "ar", en: "with" },
  { lv: "bez", en: "without" },
  { lv: "par", en: "about" },
  { lv: "priekš", en: "for" },
  { lv: "no", en: "from" },
  { lv: "uz", en: "to" },
  { lv: "pie", en: "at" },
  { lv: "līdz", en: "until" },
  { lv: "caur", en: "through" },
  { lv: "pret", en: "against" },
  { lv: "pirms", en: "before" },
  { lv: "pēc", en: "after" },
  { lv: "ap", en: "around" },
  { lv: "kopā", en: "together" },
  { lv: "atsevišķi", en: "separately" },
  { lv: "daudz", en: "many" },
  { lv: "maz", en: "few" },
  { lv: "visi", en: "all" },
  { lv: "neviens", en: "none" },
  { lv: "daži", en: "some" },
  { lv: "viens", en: "one (person)" },
  { lv: "cits", en: "other" },
  { lv: "katrs", en: "each" },
  { lv: "viens otram", en: "each other" },
  { lv: "viens pats", en: "alone" },
  { lv: "kopā", en: "together" },
  { lv: "jautājums", en: "question" },
  { lv: "atbilde", en: "answer" },
  { lv: "problēma", en: "problem" },
  { lv: "risinājums", en: "solution" },
  { lv: "darbs", en: "work (noun)" },
  { lv: "spēle", en: "game" },
  { lv: "sports", en: "sport" },
  { lv: "mūzika", en: "music" },
  { lv: "dziesma", en: "song" },
  { lv: "filma", en: "movie" },
  { lv: "attēls", en: "picture" },
  { lv: "fotogrāfija", en: "photo" },
  { lv: "krāsa", en: "color" },
  { lv: "forma", en: "shape" },
  { lv: "skaņa", en: "sound" },
  { lv: "smarža", en: "smell" },
  { lv: "garša", en: "taste" },
  { lv: "pieskāriens", en: "touch" },
  { lv: "gaisma", en: "light" },
  { lv: "ēna", en: "shadow" },
  { lv: "durvis", en: "door" },
  { lv: "logs", en: "window" },
  { lv: "siena", en: "wall" },
  { lv: "grīda", en: "floor" },
  { lv: "griesti", en: "ceiling" },
  { lv: "virsma", en: "surface" },
  { lv: "stūris", en: "corner" },
  { lv: "centrs", en: "center" },
  { lv: "malā", en: "edge" },
  { lv: "pulveris", en: "powder" },
  { lv: "šķidrums", en: "liquid" },
  { lv: "gāze", en: "gas" },
  { lv: "metāls", en: "metal" },
  { lv: "koksne", en: "wood" },
  { lv: "akmens", en: "stone" },
  { lv: "smiltis", en: "sand" },
  { lv: "zeme", en: "soil" },
  { lv: "uguns", en: "fire" },
  { lv: "ūdens", en: "water" },
  { lv: "gaiss", en: "air" },
  { lv: "ledus", en: "ice" },
  { lv: "tvaiks", en: "steam" },
  { lv: "putekļi", en: "dust" },
  { lv: "skaņa", en: "sound" },
  { lv: "klusums", en: "silence" },
  { lv: "spēks", en: "strength" },
  { lv: "vājums", en: "weakness" },
  { lv: "ātrums", en: "speed" },
  { lv: "lēnums", en: "slowness" },
  { lv: "svars", en: "weight" },
  { lv: "garums", en: "length" },
  { lv: "platums", en: "width" },
  { lv: "augstums", en: "height" },
  { lv: "dziļums", en: "depth" },
  { lv: "biezums", en: "thickness" },
  { lv: "plānums", en: "thinness" },
  { lv: "stiprums", en: "strength" },
  { lv: "vājums", en: "weakness" },
  { lv: "prieks", en: "joy" },
  { lv: "skumjas", en: "sadness" },
  { lv: "dusmas", en: "anger" },
  { lv: "bailes", en: "fear" },
  { lv: "mīlestība", en: "love" },
  { lv: "naids", en: "hate" },
  { lv: "cerība", en: "hope" },
  { lv: "sapnis", en: "dream" },
  { lv: "dzīve", en: "life" },
  { lv: "nāve", en: "death" },
];
