export const CATEGORIES = [
  {
    name: "Animals",
    words: [
      { lv: "suns", en: "dog" },
      { lv: "kaķis", en: "cat" },
      { lv: "zivs", en: "fish" },
      { lv: "putns", en: "bird" },
    ],
  },
  {
    name: "Food & Drink",
    words: [
      { lv: "maize", en: "bread" },
      { lv: "ūdens", en: "water" },
      { lv: "piens", en: "milk" },
      { lv: "ābols", en: "apple" },
      { lv: "banāns", en: "banana" },
      { lv: "apelsīns", en: "orange" },
      { lv: "vīnogas", en: "grapes" },
    ],
  },
  {
    name: "People & Family",
    words: [
      { lv: "cilvēks", en: "person" },
      { lv: "bērns", en: "child" },
      { lv: "mamma", en: "mother" },
      { lv: "tēvs", en: "father" },
      { lv: "draugs", en: "friend" },
      { lv: "vecāki", en: "parents" },
      { lv: "brālis", en: "brother" },
      { lv: "māsa", en: "sister" },
      { lv: "zēns", en: "boy" },
      { lv: "meitene", en: "girl" },
      { lv: "skolotājs", en: "teacher" },
      { lv: "students", en: "student" },
    ],
  },
  {
    name: "Nature",
    words: [
      { lv: "koks", en: "tree" },
      { lv: "jūra", en: "sea" },
      { lv: "kalns", en: "mountain" },
      { lv: "upe", en: "river" },
      { lv: "saule", en: "sun" },
      { lv: "mēness", en: "moon" },
      { lv: "zvaigzne", en: "star" },
      { lv: "debesis", en: "sky" },
      { lv: "zeme", en: "earth" },
      { lv: "mežs", en: "forest" },
      { lv: "ezers", en: "lake" },
      { lv: "zāle", en: "grass" },
      { lv: "zieds", en: "flower" },
      { lv: "auglis", en: "fruit" },
    ],
  },
  {
    name: "Adjectives",
    words: [
      { lv: "liels", en: "big" },
      { lv: "mazs", en: "small" },
      // { lv: "jauns", en: "young" },
      { lv: "vecs", en: "old" },
      { lv: "jauns", en: "new" },
      { lv: "skaists", en: "beautiful" },
      { lv: "neglīts / neskaists", en: "ugly" },
      { lv: "garš", en: "long" },
      { lv: "īss", en: "short" },
      { lv: "augsts", en: "tall" },
      { lv: "zems", en: "low" },
      // { lv: "biezs", en: "thick" },
      // { lv: "plāns", en: "thin" },
      // { lv: "smags", en: "heavy" },
      { lv: "viegls", en: "light (weight)" },
      { lv: "tumšs", en: "dark" },
      { lv: "gaišs", en: "light (bright)" },
      // { lv: "ātrs", en: "fast" },
      // { lv: "lēns", en: "slow" },
      // { lv: "tīrs", en: "clean" },
      // { lv: "netīrs", en: "dirty" },
      // { lv: "stiprs", en: "strong" },
      // { lv: "vājš", en: "weak" },
      // { lv: "draudzīgs", en: "friendly" },
      // { lv: "laimīgs", en: "happy" },
      // { lv: "skumjš", en: "sad" },
      // { lv: "dusmīgs", en: "angry" },
      // { lv: "mierīgs", en: "calm" },
      // { lv: "bailīgs", en: "afraid" },
      // { lv: "izsalcis", en: "hungry" },
      // { lv: "izslāpis", en: "thirsty" },
      // { lv: "noguris", en: "tired" },
      // { lv: "slims", en: "sick" },
      // { lv: "vesels", en: "healthy" },
      { lv: "bagāts", en: "rich" },
      { lv: "nabadzīgs", en: "poor" },
      // { lv: "gudrs", en: "smart" },
      // { lv: "muļķīgs", en: "silly" },
      // { lv: "spēcīgs", en: "powerful" },
      { lv: "mazs", en: "small" },
      { lv: "liels", en: "big" },
      { lv: "gaišs", en: "bright" },
      // { lv: "dzīvs", en: "alive" },
      // { lv: "jauns", en: "new" },
      { lv: "šaurs", en: "narrow" },
      // { lv: "plāns", en: "thin" },
      { lv: "vājš", en: "weak" },
      { lv: "spēcīgs", en: "strong" },
      { lv: "plats", en: "wide" },
      { lv: "ērts", en: "comfortable" },
      { lv: "neērts", en: "uncomfortable" },
      { lv: "mīksts", en: "soft" },
      { lv: "ciets", en: "hard" },
      { lv: "karsts", en: "hot" },
      { lv: "auksts", en: "cold" },
      { lv: "plašs", en: "spacious" },
      { lv: "dārgs", en: "expensive" },
      { lv: "lēts", en: "cheap" },
    ],
  },
  {
    name: "Verbs",
    words: [
      { lv: "būt", en: "to be" },
      { lv: "iet", en: "to go" },
      { lv: "redzēt", en: "to see" },
      { lv: "ēst", en: "to eat" },
      { lv: "dzert", en: "to drink" },
      { lv: "lasīt", en: "to read" },
      { lv: "nākt", en: "to come" },
      { lv: "dzirdēt", en: "to hear" },
      { lv: "gulēt", en: "to sleep" },
      { lv: "strādāt", en: "to work" },
      { lv: "spēlēt", en: "to play" },
      { lv: "rakstīt", en: "to write" },
      { lv: "domāt", en: "to think" },
      { lv: "zināt", en: "to know" },
      { lv: "mācīties", en: "to learn" },
      { lv: "mācīt", en: "to teach" },
      { lv: "pirkt", en: "to buy" },
      { lv: "pārdot", en: "to sell" },
      { lv: "atvērt", en: "to open" },
      { lv: "aizvērt", en: "to close" },
      { lv: "sākt", en: "to start" },
      { lv: "beigt", en: "to finish" },
      { lv: "palīdzēt", en: "to help" },
      { lv: "spēt", en: "to be able" },
      { lv: "gribēt", en: "to want" },
      { lv: "patikt", en: "to like" },
      { lv: "mīlēt", en: "to love" },
      { lv: "baidīties", en: "to fear" },
      { lv: "cerēt", en: "to hope" },
      { lv: "smaidīt", en: "to smile" },
      { lv: "smieties", en: "to laugh" },
      { lv: "raudāt", en: "to cry" },
      { lv: "sēdēt", en: "to sit" },
      { lv: "stāvēt", en: "to stand" },
      { lv: "skriet", en: "to run" },
      { lv: "peldēt", en: "to swim" },
      { lv: "lidot", en: "to fly" },
      { lv: "braukt", en: "to drive" },
      { lv: "zvanīt", en: "to call" },
      { lv: "runāt", en: "to speak" },
      { lv: "klausīties", en: "to listen" },
      { lv: "skatīties", en: "to watch" },
      { lv: "meklēt", en: "to search" },
      { lv: "atrast", en: "to find" },
      { lv: "zaudēt", en: "to lose" },
      { lv: "uzvarēt", en: "to win" },
    ],
  },
  {
    name: "Numbers",
    words: [
      { lv: "viens", en: "one" },
      { lv: "divi", en: "two" },
      { lv: "trīs", en: "three" },
      { lv: "četri", en: "four" },
      { lv: "pieci", en: "five" },
      { lv: "seši", en: "six" },
      { lv: "septiņi", en: "seven" },
      { lv: "astoņi", en: "eight" },
      { lv: "deviņi", en: "nine" },
      { lv: "desmit", en: "ten" },
    ],
  },
  {
    name: "Colors",
    words: [
      { lv: "sarkans", en: "red" },
      { lv: "zils", en: "blue" },
      { lv: "zaļš", en: "green" },
      { lv: "dzeltens", en: "yellow" },
      { lv: "balts", en: "white" },
      { lv: "melns", en: "black" },
      { lv: "brūns", en: "brown" },
      { lv: "pelēks", en: "gray" },
      { lv: "rozā", en: "pink" },
      { lv: "oranžs", en: "orange (color)" },
      { lv: "violets", en: "purple" },
      { lv: "zelts", en: "gold" },
      { lv: "sudrabs", en: "silver" },
    ],
  },
  {
    name: "Basic Phrases",
    words: [
      { lv: "jā", en: "yes" },
      { lv: "nē", en: "no" },
      { lv: "lūdzu", en: "please" },
      { lv: "paldies", en: "thank you" },
      { lv: "sveiki", en: "hello" },
      { lv: "uz redzēšanos", en: "goodbye" },
      { lv: "labrīt", en: "good morning" },
      { lv: "labdien", en: "good afternoon" },
      { lv: "labvakar", en: "good evening" },
      { lv: "ar labu nakti", en: "good night" },
      { lv: "kā jums klājas?", en: "how are you?" },
      { lv: "labi", en: "fine" },
      { lv: "slikti", en: "badly" },
      { lv: "atvainojiet", en: "excuse me" },
      { lv: "es nesaprotu", en: "I don't understand" },
      { lv: "kur ir tualete?", en: "where is the toilet?" },
      { lv: "mani sauc...", en: "my name is..." },
      { lv: "cik tas maksā?", en: "how much does it cost?" },
      { lv: "palīdziet!", en: "help!" },
      { lv: "esmu no...", en: "I am from..." },
      { lv: "varbūt", en: "maybe" },
      { lv: "nav problēmu", en: "no problem" },
      { lv: "kur jūs dzīvojat?", en: "where do you live?" },
      { lv: "es dzīvoju...", en: "I live..." },
      { lv: "cik jums ir gadi?", en: "how old are you?" },
      { lv: "man ir ... gadi", en: "I am ... years old" },
      { lv: "vai jūs runājat angliski?", en: "do you speak English?" },
      { lv: "es runāju latviski", en: "I speak Latvian" },
      { lv: "kur mēs esam?", en: "where are we?" },
      { lv: "kas tas ir?", en: "what is this?" },
      { lv: "ko jūs darāt?", en: "what are you doing?" },
      { lv: "es strādāju", en: "I am working" },
      { lv: "es mācos", en: "I am studying" },
      { lv: "vai jūs varat palīdzēt?", en: "can you help?" },
      { lv: "es nezinu", en: "I don't know" },
      { lv: "kur ir autobuss?", en: "where is the bus?" },
      { lv: "vai tas ir tālu?", en: "is it far?" },
      { lv: "vai tas ir tuvu?", en: "is it near?" },
      { lv: "vai jūs saprotat?", en: "do you understand?" },
      { lv: "es saprotu", en: "I understand" },
      { lv: "vai jūs esat latvietis?", en: "are you Latvian?" },
      { lv: "jā, es esmu latvietis", en: "yes, I am Latvian" },
      { lv: "nē, es neesmu latvietis", en: "no, I am not Latvian" },
      { lv: "vai jūs esat students?", en: "are you a student?" },
      { lv: "jā, es esmu students", en: "yes, I am a student" },
      { lv: "nē, es neesmu students", en: "no, I am not a student" },
      { lv: "vai jūs esat skolotājs?", en: "are you a teacher?" },
      { lv: "jā, es esmu skolotājs", en: "yes, I am a teacher" },
      { lv: "nē, es neesmu skolotājs", en: "no, I am not a teacher" },
      { lv: "vai jūs esat precējies?", en: "are you married?" },
      { lv: "jā, es esmu precējies", en: "yes, I am married" },
      { lv: "nē, es neesmu precējies", en: "no, I am not married" },
    ],
  },
  {
    name: "Places",
    words: [
      { lv: "māja", en: "house" },
      { lv: "skola", en: "school" },
      { lv: "pilsēta", en: "city" },
      { lv: "valsts", en: "country" },
      { lv: "iela", en: "street" },
      { lv: "tilts", en: "bridge" },
      { lv: "ceļš", en: "road" },
      { lv: "dārzs", en: "garden" },
    ],
  },
  {
    name: "Transport",
    words: [
      { lv: "mašīna", en: "car" },
      { lv: "velosipēds", en: "bicycle" },
      { lv: "autobuss", en: "bus" },
      { lv: "vilciens", en: "train" },
      { lv: "lidojums", en: "flight" },
    ],
  },
  {
    name: "Questions",
    words: [
      { lv: "kur?", en: "where?" },
      { lv: "kad?", en: "when?" },
      { lv: "kāpēc?", en: "why?" },
      { lv: "kas?", en: "what?" },
      { lv: "kā?", en: "how?" },
      { lv: "kurš?", en: "which?" },
      { lv: "cik?", en: "how much?" },
    ],
  },
  {
    name: "Time & Frequency",
    words: [
      { lv: "laiks", en: "time" },
      { lv: "diena", en: "day" },
      { lv: "nakts", en: "night" },
      { lv: "rīts", en: "morning" },
      { lv: "vakars", en: "evening" },
      { lv: "nedēļa", en: "week" },
      { lv: "mēnesis", en: "month" },
      { lv: "gads", en: "year" },
      { lv: "stunda", en: "hour" },
      { lv: "minūte", en: "minute" },
      { lv: "sekunde", en: "second" },
      { lv: "tagad", en: "now" },
      { lv: "vakar", en: "yesterday" },
      { lv: "šodien", en: "today" },
      { lv: "rīt", en: "tomorrow" },
      { lv: "vienmēr", en: "always" },
      { lv: "nekad", en: "never" },
      { lv: "bieži", en: "often" },
      { lv: "reti", en: "rarely" },
      { lv: "reizēm", en: "sometimes" },
      { lv: "drīz", en: "soon" },
      { lv: "vēlāk", en: "later" },
      { lv: "agrāk", en: "earlier" },
    ],
  },
  {
    name: "Directions & Position",
    words: [
      { lv: "augšā", en: "up" },
      { lv: "lejā", en: "down" },
      { lv: "pa kreisi", en: "left" },
      { lv: "pa labi", en: "right" },
      { lv: "priekšā", en: "in front" },
      { lv: "aizmugurē", en: "behind" },
      { lv: "tuvumā", en: "near" },
      { lv: "tālu", en: "far" },
      { lv: "blakus", en: "next to" },
      { lv: "starp", en: "between" },
      { lv: "virs", en: "above" },
      { lv: "zem", en: "below" },
    ],
  },
  {
    name: "Prepositions & Particles",
    words: [
      { lv: "ar", en: "with" },
      { lv: "bez", en: "without" },
      { lv: "par", en: "about" },
      { lv: "priekš", en: "for" },
      { lv: "no", en: "from" },
      { lv: "uz", en: "to" },
      { lv: "pie", en: "at" },
      { lv: "līdz", en: "until" },
      { lv: "caur", en: "through" },
      { lv: "pret", en: "against" },
      { lv: "ap", en: "around" },
      { lv: "kopā", en: "together" },
      { lv: "atsevišķi", en: "separately" },
    ],
  },
  {
    name: "Quantifiers",
    words: [
      { lv: "daudz", en: "many" },
      { lv: "maz", en: "few" },
      { lv: "visi", en: "all" },
      { lv: "neviens", en: "none" },
      { lv: "daži", en: "some" },
      { lv: "viens", en: "one (person)" },
      { lv: "cits", en: "other" },
      { lv: "katrs", en: "each" },
      { lv: "viens otram", en: "each other" },
      { lv: "viens pats", en: "alone" },
    ],
  },
  {
    name: "Household & Objects",
    words: [
      { lv: "durvis", en: "door" },
      { lv: "logs", en: "window" },
      { lv: "siena", en: "wall" },
      { lv: "grīda", en: "floor" },
      { lv: "griesti", en: "ceiling" },
      { lv: "virsma", en: "surface" },
      { lv: "stūris", en: "corner" },
      { lv: "centrs", en: "center" },
      { lv: "malā", en: "edge" },
      { lv: "attēls", en: "picture" },
      { lv: "fotogrāfija", en: "photo" },
    ],
  },
  {
    name: "Materials & Elements",
    words: [
      { lv: "pulveris", en: "powder" },
      { lv: "šķidrums", en: "liquid" },
      { lv: "gāze", en: "gas" },
      { lv: "metāls", en: "metal" },
      { lv: "koksne", en: "wood" },
      { lv: "akmens", en: "stone" },
      { lv: "smiltis", en: "sand" },
      { lv: "zeme", en: "soil" },
      { lv: "uguns", en: "fire" },
      { lv: "ūdens", en: "water" },
      { lv: "gaiss", en: "air" },
      { lv: "ledus", en: "ice" },
      { lv: "tvaiks", en: "steam" },
      { lv: "putekļi", en: "dust" },
    ],
  },
  {
    name: "Senses & Shapes",
    words: [
      { lv: "krāsa", en: "color" },
      { lv: "forma", en: "shape" },
      { lv: "skaņa", en: "sound" },
      { lv: "smarža", en: "smell" },
      { lv: "garša", en: "taste" },
      { lv: "pieskāriens", en: "touch" },
      { lv: "gaisma", en: "light" },
      { lv: "ēna", en: "shadow" },
    ],
  },
  {
    name: "Entertainment & Media",
    words: [
      { lv: "spēle", en: "game" },
      { lv: "sports", en: "sport" },
      { lv: "mūzika", en: "music" },
      { lv: "dziesma", en: "song" },
      { lv: "filma", en: "movie" },
    ],
  },
  {
    name: "Abstract Concepts",
    words: [
      { lv: "jautājums", en: "question" },
      { lv: "atbilde", en: "answer" },
      { lv: "problēma", en: "problem" },
      { lv: "risinājums", en: "solution" },
      { lv: "sāpes", en: "pain" },
      { lv: "prieks", en: "joy" },
      { lv: "mīlestība", en: "love (noun)" },
      { lv: "naids", en: "hate" },
      { lv: "bailes", en: "fear" },
      { lv: "cerība", en: "hope" },
      { lv: "sapnis", en: "dream" },
      { lv: "dzīve", en: "life" },
      { lv: "nāve", en: "death" },
    ],
  },
  {
    name: "Measurements & Properties",
    words: [
      { lv: "spēks", en: "strength" },
      { lv: "vājums", en: "weakness" },
      { lv: "ātrums", en: "speed" },
      { lv: "lēnums", en: "slowness" },
      { lv: "svars", en: "weight" },
      { lv: "garums", en: "length" },
      { lv: "platums", en: "width" },
      { lv: "augstums", en: "height" },
      { lv: "dziļums", en: "depth" },
      { lv: "biezums", en: "thickness" },
      { lv: "plānums", en: "thinness" },
    ],
  },
];

// Derived convenience export used by UI: includes an "All" category
const ALL = CATEGORIES.flatMap((c) => c.words);
export const categories = [{ name: "All", words: ALL }, ...CATEGORIES];
